// <auto-generated />
using System;
using InfoTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfoTrack.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("InfoTrack.Api.Models.LocationBaseline", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("LastVerified").HasColumnType("TEXT");
                b.Property<int>("LastKnownCount").HasColumnType("INTEGER");
                b.Property<string>("LastHealth").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Location").IsRequired().HasColumnType("TEXT");
                b.Property<string>("SiteId").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Location", "SiteId").IsUnique();
                b.ToTable("LocationBaselines");
            });

            modelBuilder.Entity("InfoTrack.Api.Models.SearchRun", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime?>("CompletedAt").HasColumnType("TEXT");
                b.Property<string>("Locations").IsRequired().HasColumnType("TEXT")
                    .HasConversion<string>();
                b.Property<DateTime>("StartedAt").HasColumnType("TEXT");
                b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("SearchRuns");
            });

            modelBuilder.Entity("InfoTrack.Api.Models.SolicitorRecord", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Address").HasColumnType("TEXT");
                b.Property<string>("Email").HasColumnType("TEXT");
                b.Property<bool>("IsNew").HasColumnType("INTEGER");
                b.Property<string>("Location").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ParseHealth").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Phone").HasColumnType("TEXT");
                b.Property<double?>("Rating").HasColumnType("REAL");
                b.Property<int?>("ReviewCount").HasColumnType("INTEGER");
                b.Property<int>("SearchRunId").HasColumnType("INTEGER");
                b.Property<string>("SiteId").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Website").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("SearchRunId", "Location");
                b.ToTable("SolicitorRecords");
            });

            modelBuilder.Entity("InfoTrack.Api.Models.SolicitorRecord", b =>
            {
                b.HasOne("InfoTrack.Api.Models.SearchRun", "SearchRun")
                    .WithMany("Results")
                    .HasForeignKey("SearchRunId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("SearchRun");
            });

            modelBuilder.Entity("InfoTrack.Api.Models.SearchRun", b =>
            {
                b.Navigation("Results");
            });
#pragma warning restore 612, 618
        }
    }
}
